name: Anti-Whale Cloud Deploy
on:
  push:
    branches: [ main ] # Стартира автоматично, когато промениш main.py

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }} # Използваме твоя готов ключ!

    - name: Run Anti-Whale Logic
      run: python main.py # Тества системата за китове преди качване

